# Generated by Django 4.1.9 on 2023-11-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HighScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("usr_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ScoreTable",
            fields=[
                ("usr_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(default="other", max_length=10)),
                ("score", models.IntegerField()),
                ("timing", models.IntegerField()),
            ],
        ),
    ]
